create table companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    name varchar(180) not null unique,
    industry varchar(120),
    website varchar(255),
    logo_url varchar(255),
    company_size varchar(80),
    subscription_plan varchar(80) not null default 'FREE',
    status varchar(40) not null default 'ACTIVE'
);

create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    email varchar(180) not null unique,
    password varchar(255) not null,
    phone varchar(40),
    avatar_url varchar(255),
    role varchar(40) not null,
    status varchar(40) not null,
    company_id bigint references companies(id),
    failed_login_attempts integer not null default 0,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    password_changed_at timestamp with time zone
);
create index idx_users_company on users(company_id);
create index idx_users_role on users(role);

create table trainer_profiles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null unique references users(id),
    bio text,
    expertise text,
    portfolio_url varchar(255),
    social_links text,
    rating numeric(3,2) not null default 0,
    total_trainings integer not null default 0
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone
);
create index idx_refresh_tokens_user on refresh_tokens(user_id);

create table password_reset_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    used_at timestamp with time zone
);
create index idx_password_reset_tokens_user on password_reset_tokens(user_id);

create table teams (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    name varchar(140) not null,
    company_id bigint not null references companies(id),
    manager_id bigint references users(id),
    description text,
    constraint uk_teams_company_name unique (company_id, name)
);
create index idx_teams_company on teams(company_id);

create table team_members (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    team_id bigint not null references teams(id) on delete cascade,
    company_id bigint not null references companies(id),
    position varchar(120),
    joined_at timestamp with time zone not null,
    constraint uk_team_members_team_user unique (team_id, user_id)
);
create index idx_team_members_company on team_members(company_id);
create index idx_team_members_user on team_members(user_id);

create table notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    title varchar(180) not null,
    message text not null,
    type varchar(60) not null,
    is_read boolean not null default false
);
create index idx_notifications_user_created on notifications(user_id, created_at);

create table trainings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    trainer_id bigint not null references users(id),
    title varchar(220) not null,
    slug varchar(260) not null unique,
    short_description varchar(500),
    description text,
    thumbnail_url varchar(255),
    intro_video_url varchar(255),
    category varchar(120),
    level varchar(40) not null,
    language varchar(20) not null default 'en',
    duration_minutes integer not null default 0,
    price numeric(12,2) not null default 0,
    status varchar(40) not null default 'DRAFT'
);
create index idx_trainings_trainer on trainings(trainer_id);
create index idx_trainings_filters on trainings(status, category, level);

create table lessons (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    training_id bigint not null references trainings(id) on delete cascade,
    title varchar(220) not null,
    content text,
    video_url varchar(255),
    duration_minutes integer not null default 0,
    order_index integer not null default 0,
    preview boolean not null default false
);
create index idx_lessons_training_order on lessons(training_id, order_index);

create table quizzes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    lesson_id bigint not null unique references lessons(id) on delete cascade,
    title varchar(220) not null,
    passing_score integer not null,
    max_attempts integer not null
);

create table questions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    quiz_id bigint not null references quizzes(id) on delete cascade,
    question_text text not null,
    type varchar(40) not null,
    order_index integer not null default 0
);
create index idx_questions_quiz_order on questions(quiz_id, order_index);

create table answer_options (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    question_id bigint not null references questions(id) on delete cascade,
    text text not null,
    correct boolean not null default false
);
create index idx_answer_options_question on answer_options(question_id);

create table training_assignments (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    training_id bigint not null references trainings(id),
    company_id bigint not null references companies(id),
    team_id bigint references teams(id),
    learner_id bigint references users(id),
    assigned_by bigint not null references users(id),
    due_date date,
    status varchar(40) not null default 'ACTIVE'
);
create index idx_assignments_company on training_assignments(company_id);
create index idx_assignments_learner on training_assignments(learner_id);
create index idx_assignments_team on training_assignments(team_id);

create table learner_progress (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    learner_id bigint not null references users(id),
    training_id bigint not null references trainings(id),
    completed_lessons integer not null default 0,
    progress_percentage numeric(5,2) not null default 0,
    status varchar(40) not null default 'NOT_STARTED',
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    approved_at timestamp with time zone,
    approved_by bigint references users(id),
    constraint uk_progress_learner_training unique (learner_id, training_id)
);

create table lesson_progress (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    learner_id bigint not null references users(id),
    lesson_id bigint not null references lessons(id),
    completed boolean not null default false,
    completed_at timestamp with time zone,
    constraint uk_lesson_progress_learner_lesson unique (learner_id, lesson_id)
);

create table quiz_attempts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    learner_id bigint not null references users(id),
    quiz_id bigint not null references quizzes(id),
    score integer not null,
    passed boolean not null,
    attempt_number integer not null,
    submitted_at timestamp with time zone not null
);
create index idx_quiz_attempts_learner_quiz on quiz_attempts(learner_id, quiz_id);

create table stored_files (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null unique,
    content_type varchar(255) not null,
    file_size bigint not null,
    category varchar(60) not null,
    storage_path varchar(1000) not null,
    uploaded_by bigint references users(id)
);

create table certificates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    certificate_number varchar(80) not null unique,
    learner_id bigint not null references users(id),
    training_id bigint not null references trainings(id),
    trainer_id bigint not null references users(id),
    issued_at timestamp with time zone not null,
    file_url varchar(255) not null,
    file_id bigint not null references stored_files(id),
    verification_code varchar(80) not null unique,
    constraint uk_certificates_learner_training unique (learner_id, training_id)
);

create table subscription_plans (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    name varchar(120) not null unique,
    price numeric(12,2) not null,
    max_users integer not null,
    max_teams integer not null,
    max_trainings integer not null,
    features text
);

create table company_subscriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    company_id bigint not null references companies(id),
    plan_id bigint not null references subscription_plans(id),
    status varchar(40) not null,
    started_at timestamp with time zone not null,
    expires_at timestamp with time zone
);

insert into subscription_plans (created_at, updated_at, name, price, max_users, max_teams, max_trainings, features)
values
    (current_timestamp, current_timestamp, 'FREE', 0, 25, 3, 5, 'Starter LMS features'),
    (current_timestamp, current_timestamp, 'GROWTH', 99, 250, 25, 50, 'Advanced teams and reporting'),
    (current_timestamp, current_timestamp, 'ENTERPRISE', 499, 5000, 500, 1000, 'Enterprise limits and support');
