create table email_verification_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    verified_at timestamp with time zone
);
create index idx_email_verification_hash_active on email_verification_tokens(token_hash, verified_at, expires_at);
create index idx_email_verification_user on email_verification_tokens(user_id);

create table invitation_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    user_id bigint not null references users(id),
    team_id bigint not null references teams(id),
    company_id bigint not null references companies(id),
    invited_by bigint not null references users(id),
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    accepted_at timestamp with time zone
);
create index idx_invitation_hash_active on invitation_tokens(token_hash, accepted_at, expires_at);
create index idx_invitation_company_team on invitation_tokens(company_id, team_id);

create table audit_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    action varchar(80) not null,
    actor_user_id bigint,
    target_user_id bigint,
    company_id bigint,
    resource_type varchar(120),
    resource_id bigint,
    outcome varchar(80),
    details text
);
create index idx_audit_events_company_created on audit_events(company_id, created_at);
create index idx_audit_events_actor_created on audit_events(actor_user_id, created_at);
create index idx_audit_events_action_created on audit_events(action, created_at);
