alter table quizzes
    add column published boolean not null default false;

alter table trainer_profiles
    add column cv_url varchar(255);

alter table trainer_profiles
    add column certificate_url varchar(255);

alter table trainer_profiles
    add column diploma_url varchar(255);

create table lesson_resources (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(255),
    updated_by varchar(255),
    lesson_id bigint not null,
    file_id bigint not null,
    file_url varchar(1000) not null,
    file_type varchar(120) not null,
    original_name varchar(255) not null,
    size bigint not null,
    constraint fk_lesson_resources_lesson foreign key (lesson_id) references lessons(id) on delete cascade,
    constraint fk_lesson_resources_file foreign key (file_id) references stored_files(id) on delete cascade
);

create index idx_lesson_resources_lesson_id on lesson_resources(lesson_id);
