package com.example.lms.audit.entity;

public enum AuditAction {
    USER_REGISTERED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGE_CODE_SENT,
    PASSWORD_CHANGED,
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    TRAINING_CREATED,
    TRAINING_PUBLISHED,
    CERTIFICATE_GENERATED
}
